### ISSUE TITLE
MalformedParameterizedTypeException on parsing routes

### ISSUE THREAD

**Issue by vmorarian** [swagger-spray/swagger-spray#4]
Hi,

I was able to isolate this problem. It happens on adding https://github.com/pjfanning/swagger-spray-sample/blob/master/src/main/scala/com/example/spray/add/AddService.scala#L45
`protected def fake(list: scalaz.NonEmptyList[Option[String]]): Route = ???`

It looks like that problem is related to scalaz.NonEmptyList (scalaz 7.1.0)

```
java.lang.reflect.MalformedParameterizedTypeException
        at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
        at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
        at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
        at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(ConstructorRepository.java:94)
        at java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:283)
        at java.lang.reflect.Method.getGenericParameterTypes(Method.java:283)
        at io.swagger.util.ReflectionUtils.findMethod(ReflectionUtils.java:104)
        at io.swagger.util.ReflectionUtils.getOverriddenMethod(ReflectionUtils.java:85)
        at io.swagger.util.ReflectionUtils.getAnnotation(ReflectionUtils.java:188)
        at io.swagger.jaxrs.Reader.read(Reader.java:278)
        at io.swagger.jaxrs.Reader.read(Reader.java:145)
        at com.github.swagger.spray.SwaggerHttpService$class.swagger(SwaggerHttpService.scala:66)
        at com.example.spray.swagger.SwaggerDocService.swagger(SwaggerDocService.scala:12)
        at com.github.swagger.spray.SwaggerHttpService$$anonfun$routes$1.apply(SwaggerHttpService.scala:75)
        at com.github.swagger.spray.SwaggerHttpService$$anonfun$routes$1.apply(SwaggerHttpService.scala:75)
        at spray.routing.directives.RouteDirectives$$anonfun$complete$1$$anon$3.apply(RouteDirectives.scala:49)
        at spray.routing.directives.RouteDirectives$$anonfun$complete$1$$anon$3.apply(RouteDirectives.scala:48)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
        at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
        at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
        at spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102)
        at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
        at spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102)
        at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
        at spray.routing.RequestContext.reject(RequestContext.scala:202)
        at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:63)
        at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:62)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
        at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
        at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
        at spray.routing.RequestContext.reject(RequestContext.scala:202)
        at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:63)
        at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:62)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
        at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)
        at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72)
        at spray.routing.RequestContext.reject(RequestContext.scala:202)
        at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:63)
        at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:62)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30)
        at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
        at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:35)
        at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:33)
        at spray.routing.HttpServiceBase$class.runSealedRoute$1(HttpService.scala:36)
        at spray.routing.HttpServiceBase$$anonfun$runRoute$1.applyOrElse(HttpService.scala:46)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at spray.routing.SimpleRoutingApp$$anonfun$1$$anon$1.aroundReceive(SimpleRoutingApp.scala:54)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by vmorarian** [comment]
Ugh, found root of this behaviour https://github.com/scalaz/scalaz/pull/932/files
